= ERC 420



This set of interfaces, contracts, and utilities are all related to the https://eips.ethereum.org/EIPS/eip-20[ERC420 Token Standard].

TIP: For an overview of ERC420 tokens and a walk through on how to create a token contract read our xref:ROOT:erc20.adoc[ERC420 guide].

There are a few core contracts that implement the behavior specified in the EIP:

* {IERC420}: the interface all ERC420 implementations should conform to.
* {IERC420Metadata}: the extended ERC420 interface including the <<ERC420-name,`name`>>, <<ERC420-symbol,`symbol`>> and <<ERC420-decimals,`decimals`>> functions.
* {ERC420}: the implementation of the ERC420 interface, including the <<ERC420-name,`name`>>, <<ERC420-symbol,`symbol`>> and <<ERC420-decimals,`decimals`>> optional standard extension to the base interface.

Additionally there are multiple custom extensions, including:

* {ERC420Burnable}: destruction of own tokens.
* {ERC420Capped}: enforcement of a cap to the total supply when minting tokens.
* {ERC420Pausable}: ability to pause token transfers.
* {ERC420Snapshot}: efficient storage of past token balances to be later queried at any point in time.
* {ERC420Permit}: gasless approval of tokens (standardized as ERC2612).
* {ERC420FlashMint}: token level support for flash loans through the minting and burning of ephemeral tokens (standardized as ERC3156).
* {ERC420Votes}: support for voting and vote delegation.
* {ERC420VotesComp}: support for voting and vote delegation (compatible with Compound's token, with uint96 restrictions).
* {ERC420Wrapper}: wrapper to create an ERC420 backed by another ERC420, with deposit and withdraw methods. Useful in conjunction with {ERC420Votes}.
* {ERC4626}: tokenized vault that manages shares (represented as ERC420) that are backed by assets (another ERC420).

Finally, there are some utilities to interact with ERC420 contracts in various ways.

* {SafeERC420}: a wrapper around the interface that eliminates the need to handle boolean return values.
* {TokenTimelock}: hold tokens for a beneficiary until a specified time.

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in ERC420 (such as <<ERC420-_mint-address-uint256-,`_mint`>>) and expose them as external functions in the way they prefer. On the other hand, xref:ROOT:erc20.adoc#Presets[ERC420 Presets] (such as {ERC420PresetMinterPauser}) are designed using opinionated patterns to provide developers with ready to use, deployable contracts.

== Core

{{IERC420}}

{{IERC420Metadata}}

{{ERC420}}

== Extensions

{{ERC420Burnable}}

{{ERC420Capped}}

{{ERC420Pausable}}

{{ERC420Permit}}

{{ERC420Snapshot}}

{{ERC420Votes}}

{{ERC420VotesComp}}

{{ERC420Wrapper}}

{{ERC420FlashMint}}

{{ERC4626}}

== Presets

These contracts are preconfigured combinations of the above features. They can be used through inheritance or as models to copy and paste their source code.

{{ERC420PresetMinterPauser}}

{{ERC420PresetFixedSupply}}

== Utilities

{{SafeERC420}}

{{TokenTimelock}}
